export default {
  countries: {
    // Move Ellas between GI ("Gibraltar") and Greenland, since it has been relabeled as "Greece"
    values: [
      'unknown',
      'Afghanistan',
      'AX',
      'AL',
      'Algeria',
      'American Samoa',
      'AD',
      'AO',
      'AI',
      'AQ',
      'Antigua',
      'Antigua and Barbuda',
      'Argentina',
      'Armenia',
      'AW',
      'Australia',
      'AT',
      'AZ',
      'BS',
      'BH',
      'BD',
      'BB',
      'BY',
      'Belgium',
      'Belize',
      'BJ',
      'Bermuda',
      'BT',
      'Bolivia',
      'BQ',
      'Borneo',
      'BA',
      'BW',
      'BV',
      'Brazil',
      'IO',
      'Brunei',
      'BG',
      'BF',
      'BI',
      'Cambodia',
      'Cameroon',
      'Canada',
      'CV',
      'KY',
      'CF',
      'TD',
      'Chile',
      'China',
      'CX',
      'CC',
      'Colombia',
      'KM',
      'CG',
      'Cook Islands',
      'Costa Rica',
      'CI',
      'Croatia',
      'Cuba',
      'CW',
      'CY',
      'CZ',
      'D R Congo',
      'Denmark',
      'DJ',
      'DM',
      'Dominican Republic',
      'Ecuador',
      'EG',
      'El Salvador',
      'Equatorial Guinea',
      'ER',
      'Espana',
      'EE',
      'ET',
      'FK',
      'FO',
      'Fiji',
      'Finland',
      'France',
      'GF',
      'PF',
      'TF',
      'GA',
      'GM',
      'GE',
      'Germany',
      'GH',
      'GI',
      'Ellas',
      'Greenland',
      'GD',
      'Guadeloupe',
      'GU',
      'Guatemala',
      'GG',
      'GN',
      'GW',
      'Guyana',
      'Haiti',
      'HM',
      'Hispaniola',
      'VA',
      'Honduras',
      'HK',
      'HN',
      'Iceland',
      'India',
      'Indonesia',
      'Iran',
      'IQ',
      'Ireland',
      'IM',
      'Israel',
      'Italy',
      'Jamaica',
      'Japan',
      'JE',
      'Jordan',
      'KZ',
      'Kenya',
      'KI',
      'KP',
      'KW',
      'KG',
      'LA',
      'LV',
      'Lebanon',
      'LS',
      'LR',
      'LY',
      'LI',
      'LT',
      'LU',
      'MO',
      'MK',
      'Madagascar',
      'Malawi',
      'Malaysia',
      'MV',
      'ML',
      'MT',
      'Marshall Islands',
      'MQ',
      'MR',
      'MU',
      'YT',
      'Mexico',
      'Micronesia',
      'MD',
      'MC',
      'Mongolia',
      'ME',
      'MS',
      'Morocco',
      'MZ',
      'Myanmar',
      'Namibia',
      'NR',
      'Nepal',
      'Netherlands Antilles',
      'Netherlands',
      'New Caledonia',
      'New Zealand',
      'Nicaragua',
      'NE',
      'NG',
      'Nihon',
      'Niue',
      'NF',
      'MP',
      'Norway',
      'OM',
      'Pakistan',
      'PW',
      'PS',
      'Panama',
      'Papua New Guinea',
      'Paraguay',
      'Peru',
      'Philippines',
      'PN',
      'PL',
      'Polynesia',
      'Polynesie francaise',
      'Portugal',
      'Prathet Thai',
      'Puerto Rico',
      'QA',
      'Republica Dominicana',
      'Reunion',
      'RO',
      'Russia',
      'RW',
      'BL',
      'Saint Helena',
      'KN',
      'Saint Lucia',
      'MF',
      'PM',
      'VC',
      'Samoa',
      'SM',
      'ST',
      'SA',
      'Scotland',
      'SN',
      'RS',
      'Seychelles',
      'SL',
      'SG',
      'SX',
      'SK',
      'Slovenia',
      'SO',
      'Solomon Islands',
      'South Africa',
      'GS',
      'South Korea',
      'SS',
      'Spain',
      'Sri Lanka',
      'Sudan',
      'Suriname',
      'SJ',
      'SZ',
      'Sweden',
      'CH',
      'Syria',
      'Taiwan',
      'TJ',
      'Tanzania',
      'Thailand',
      'TL',
      'TG',
      'TK',
      'Tonga',
      'Trinidad and Tobago',
      'TN',
      'Turkey',
      'TM',
      'TC',
      'TV',
      'Uganda',
      'UA',
      'AE',
      'United Kingdom',
      'UM',
      'Uruguay',
      'USA',
      'UZ',
      'Vanuatu',
      'Venezuela',
      'Viet Nam',
      'VG',
      'Virgin Islands',
      'WF',
      'EH',
      'Western Samoa',
      'YE',
      'ZM',
      'Zhonghua',
      'ZW',
    ],
  },
};
